export const USER_SIGN_REQUEST = 'USER_SIGN_REQUEST'
export const USER_SIGN_SUCCESS = 'USER_SIGN_SUCCESS'
export const USER_SIGN_FAIL = 'USER_SIGN_FAIL'

export const USER_REGISTER_REQUEST = 'USER_SIGN_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_SIGN_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_SIGN_FAIL'

export const USER_SIGN_OUT = 'USER_SIGN_OUT'

export const USER_SIGN_OUT_REGISTER = 'USER_SIGN_OUT_REGISTER'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'
