export const USER_SIGN_REQUEST = "USER_SIGN_REQUEST";
export const USER_SIGN_SUCCESS = "USER_SIGN_SUCCESS";
export const USER_SIGN_FAIL = "USER_SIGN_FAIL";

export const USER_REGISTER_REQUEST = "USER_SIGN_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_SIGN_SUCCESS";
export const USER_REGISTER_FAIL = "USER_SIGN_FAIL";

export const USER_SIGN_OUT = "USER_SIGN_OUT";

export const USER_SIGN_OUT_REGISTER = "USER_SIGN_OUT_REGISTER";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_TOPSELLERS_LIST_REQUEST = "USER_TOPSELLERS_LIST_REQUEST";
export const USER_TOPSELLERS_LIST_SUCCESS = "USER_TOPSELLERS_LIST_SUCCESS";
export const USER_TOPSELLERS_LIST_FAIL = "USER_LIST_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const USER_DELETE_REQUEST = "DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "DELETE_SUCCESS";
export const USER_DELETE_FAIL = "DELETE_FAIL";
export const USER_DELETE_RESET = "DELETE_RESET";
export const USER_ADDRESS_MAP_CONFIRM = "USER_ADDRESS_MAP_CONFIRM";
